version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - production

  nextjs:
    env_file:
      - .env
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app
      - /app/node_modules
    networks:
      - production

networks:
  production:
    driver: bridge
